### ISSUE TITLE
programmatically extract direct link

### ISSUE THREAD

**Issue by moshed** [denkc/mlbvideoconverterbot#1]
I cant for the life of me see how to extract a direct link from MLBs new format videos as there is no content ID to speak of (for instance below link). Any chance you can help me out? 

https://www.mlb.com/video/garrett-cooper-s-two-home-runs

**Comment by denkc** [comment]
I know this is two years late, but I didn't see your comment until now.  If you check out the source of the page, you'll find some mp4 and streamable links in a few spots.  The code will find the JSON-encoded links for the video, and you can test it out with:

```
$ python mlb.py https://www.mlb.com/video/garrett-cooper-s-two-home-runs
    match https://www.mlb.com/video/garrett-cooper-s-two-home-runs found: https://www.mlb.com/video/garrett-cooper-s-two-home-runs
[["Video: Garrett Cooper's two home runs", '[Streamable Link](https://streamable.com/m/garrett-cooper-s-two-home-runs)', '[High Definition](https://mlb-cuts-diamond.mlb.com/FORGE/2021/2021-07/07/919acd39-3d75243f-2248916e-csvm-diamondx64-asset_1280x720_59_16000K.mp4) (172.02 MB)', '[Standard Definiton](https://mlb-cuts-diamond.mlb.com/FORGE/2021/2021-07/07/919acd39-3d75243f-2248916e-csvm-diamondx64-asset_1280x720_59_4000K.mp4) (44.62 MB)', '___________']]
```
